# Generated by Django 5.2.7 on 2025-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customeuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='status',
            field=models.CharField(default='active', max_length=100, null=True),
        ),
    ]
