# Generated by Django 5.2.7 on 2025-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customeuser_blocked_customeuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
