# Generated by Django 5.2.7 on 2025-10-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customeuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=20, null=True),
        ),
    ]
