# Generated by Django 5.2.7 on 2025-10-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customeuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=20),
        ),
    ]
