# Generated by Django 5.2.7 on 2025-10-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customeuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeuser',
            managers=[
            ],
        ),
    ]
