# Generated by Django 5.2.7 on 2025-11-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_ordermodel_address_ordermodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('COD', 'Cash on Delivery'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe')], default='RAZORPAY', max_length=20),
        ),
    ]
