# Generated by Django 5.2.7 on 2025-10-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbenFoot', '0004_wishlistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='is_new',
            field=models.BooleanField(),
        ),
    ]
