# Generated by Django 5.2.7 on 2025-10-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbenFoot', '0005_alter_productmodel_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='is_new',
            field=models.CharField(choices=[('new', 'New'), (' ', ' ')], max_length=20),
        ),
    ]
