# Generated by Django 5.2.7 on 2025-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbenFoot', '0010_alter_productmodel_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
