# Generated by Django 5.2.7 on 2025-11-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrbenFoot', '0013_contactmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
