# Generated by Django 5.2.7 on 2025-11-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrbenFoot', '0014_alter_contactmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
